name: hive_database_service
description: "A new Flutter module project."
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

