name: hive_database_service
description: "A new Flutter module project."
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

